from pydantic import BaseModel, Field
from typing import Optional
from ome_types._autogenerated.ome_2016_06 import OME, StructuredAnnotations, XMLAnnotation
import instructor
from openai import OpenAI
import time
import sys
import importlib
import ast
from ome_types import from_xml, to_xml
from metagpt.predictors.predictor_template import PredictorTemplate
import metagpt.utils.utils as utils

class PredictorSimple(PredictorTemplate):
    """
    TODO: Add docstring
    """
    def __init__(self, raw_meta: str) -> None:
        super().__init__()
        self.raw_metadata = raw_meta
        self.full_message = "The raw data is: \n" + str(self.raw_metadata)
        self.prompt = """
        You are part of a toolchain designed to predict metadata for the OME model, specifically the structured annotations part.
        You will be interacting with other toolchain components, therefore asking questions or providing any human-readable output is not necessary.
        You should concisely and structured document your thought process for logging purposes. mark those as "thoughts".
        The toolchain is a Tree structure of models, designed with the OME schema in mind.
        This means each node has a predictor such as yourself, and will be predicting the metadata for a submodel of the OME schema.
        One such submodel could be the  XMLAnnotation node.
        The tree structure is designed to predict the metadata in a bottom-up manner, starting from the lower level node.
        This way there are no missing dependencies when predicting the metadata.
        Incoming metadata will be provided in raw format, which means a list of key-value pairs.
        Your task will be to translate these key-value pairs to the appropriate OME schema property.
        Try to figure out which property is which by looking at the schema and the raw metadata in a holistic manner.
        The function call arguments you were given are the corresponding schema snippet you are supposed to fill out, remember only the highest level; the lower levels provided are only for validation and context.
        Since this is a hard problem, I will need you to think step by step and use chain of thought.
        Here is the structure of how to approach the problem step by step:
        1. Look at the raw metadata, which properties can not be served by the ome data model and therefore should be added as structured annotations?
        2. Figure out if you can groupt these properties in a hierarchical manner, do they cluster together?
        3. Come to a conclusion how you want to structure the metadata.
        4. Call the XMLAnnotationFunction function with the structured annotations as xml Json.
        It is very well possible some fields remain empty.
        Remember to solve this problem step by step and use chain of thought to solve it.
        Again, you are not interacting with a human but are part of a chain of tools that are supposed to solve this problem.
        Under no circumstances can you ask questions.
        You will have to decide on your own. ONLY EVER RESPOND WITH THE JSON FUNCTION CALL.
        If you understood all of this, and will follow the instructions, answer with "." and wait for the first metadata to be provided.
        Use the provided function to solve the task. YOU NEED TO CALL THE FUNCTION TO SOLVE THE TASK. The chat response will be ignored.
        """
        self.pred_prompt = """
        You are a tool designed to predict metadata for the OME
        model.
        Your task will be to take raw metadata in the form of a dictionary of key-value pairs
        and put them into well formed OME XML.
        The goal here is to understand the meaning of the key value pairs and infer the correct ome properties.
        Importantly, always structure the metadata to follow the ome datamodel.
        Try to understnad exactly how the metadata properties are
        related to each other and make sense of them.
        Try to figure out a good structure by looking at the raw metadata in a
        holistic manner.
        Furthermore a file search function is provided with which you can 
        look at the ome schema to make sure you produce valid metadata.
        Always use the tool to get reliable results.
        Since this is a hard problem, I will need you to think step by step and use chain of thought.
        Before you produce actual metadata, carefully analyze the probmlem, come up with a plan and structure.
        Here is the structure of how to approach the problem step by step:
        1. Look at the ome xml schema.
        2. Look at the raw metadata.
        3. Which proerties from the key value pairs map to which ome properties?
        4. Discard any properties that are not part of the ome schema.
        5. Generate the well formed ome xml
        Remember to solve this problem step by step and use chain of thought to solve it.
        You are not interacting with a human but are part of a larger pipeline, therefore you dont need to "chat".
        Under no circumstances can you ask questions.
        To return your response use the OMEXMLResponse function, which helps you to create a consistent output.
        The OMEXMLResponse function has a ome_xml field, which you should fill with the well formed OME XML.
        ALWAYS USE THE FUNCTION TO PRODUCE RELIABLE OUTPUTS.
        You will have to decide on your own. ONLY EVER RESPOND WITH THE WELL FORMED OME XML.
        Use the provided functions to solve the task. YOU NEED TO CALL THE FUNCTIONs TO SOLVE THE TASK. The chat response will be ignored.
        If you understood all of this, and will follow the instructions, answer with "." and wait for the metadata to be provided.
        """

    
    def predict(self) -> dict:
        """
        TODO: Add docstring
        """
        print(f"Predicting for {self.name}, attempt: {self.attempts}")

        self.init_thread()
        self.init_vector_store()
        self.init_assistant()   
        self.init_run()
        response, cost = None, None
        try:
            self.add_attempts()
            if self.run.status == 'completed':
                response = self.client.beta.threads.messages.list(
                    thread_id=self.thread.id
                )
                response = response.data[0].content[0].text.value[7:][:-4]
                cost = self.get_cost(run=self.run)
            elif self.run.status == 'requires_action':
                response = self.run.required_action.submit_tool_outputs.tool_calls[0]
                response = ast.literal_eval(response.function.arguments)
                response = response['ome_xml']

            test_ome_pred = from_xml(response)
        except Exception as e:
            response = None
            print(f"There was an exception in the {self.name}" ,e)
            if self.attempts < self.max_attempts:
                print(f"Retrying {self.name}...")
                self.clean_assistants()   
                return self.predict()
            else:
                print(f"Failed {self.name} after {self.attempts} attempts.")
        
        self.clean_assistants()        
        return response, cost, self.attempts
    
    def init_run(self):
        self.run = self.client.beta.threads.runs.create(
            thread_id=self.thread.id,
            assistant_id=self.assistant.id,
            tool_choice={"type": "file_search", "type": "function", "function": {"name": "OMEXMLResponse"}},
            temperature=0.0,
            )
        
        end_status = ["completed", "requires_action", "failed"]
        while self.run.status not in end_status:
            print(self.run.status)
            time.sleep(5)
            self.run = self.client.beta.threads.runs.retrieve(
                thread_id=self.thread.id,
                run_id=self.run.id
                )
            
        print(self.run.status)
        
    def init_assistant(self):
        self.assistant = self.client.beta.assistants.create(
            name="OME XML Annotator",
            description="An assistant to predict OME XML annotations from raw metadata",
            instructions=self.pred_prompt,
            model=self.model,
            tools=[{"type": "file_search"}, utils.openai_schema(self.OMEXMLResponse)],
            tool_resources={"file_search": {"vector_store_ids": [self.vector_store.id]}}
        )
        self.assistants.append(self.assistant)

    def init_thread(self):
        self.thread = self.client.beta.threads.create(messages=[{"role": "user", "content": self.pred_prompt},
                                                                {"role": "assistant", "content": "."},
                                                                {"role": "user", "content": self.full_message}])
        self.threads.append(self.thread)

    def init_vector_store(self):
        self.vector_store = self.client.beta.vector_stores.create(
            name="OME XML Schema",
        )
        file_paths = ["/home/aaron/Documents/Projects/MetaGPT/in/schema/ome_xsd.txt"]
        file_streams = [open(path, "rb") for path in file_paths]

        file_batch = self.client.beta.vector_stores.file_batches.upload_and_poll(
            vector_store_id=self.vector_store.id, files=file_streams
            )
        self.vector_stores.append(self.vector_store)

    class OMEXMLResponse(BaseModel):
        """
        The response to the OME XML annotation
        """
        ome_xml: Optional[str] = Field(None, description="The well formed OME XML starting with <OME> and ending with </OME>")
