"""
This module contains the PredictorNetwork class, which uses a network of predictors
to process, annotate, and merge metadata for microscopy images.
"""

from typing import Optional, Tuple, Any
from ome_types._autogenerated.ome_2016_06 import StructuredAnnotations

from metagpt.predictors.predictor_template import PredictorTemplate
from metagpt.predictors.predictor_simple_annotator import PredictorSimpleAnnotation
from metagpt.predictors.predictor_simple import PredictorSimple
from metagpt.predictors.predictor_seperator import PredictorSeperator
import metagpt.utils.utils as utils

class PredictorNetwork(PredictorTemplate):
    """
    A predictor class that uses a network of predictors to process and annotate metadata.

    This predictor approach uses three assistants:
    1. A separator to split the raw metadata into already contained and new metadata.
    2. An annotator to predict structured annotations from the new metadata.
    3. A simple predictor to process the remaining metadata.
    """
    
    def __init__(self, raw_meta: str) -> None:
        """
        Initialize the PredictorNetwork.

        Args:
            raw_meta (str): The raw metadata to be processed and annotated.
        """
        super().__init__()
        self.raw_metadata = raw_meta
        self.assistants = [
            "predictor_seperator",
            "predictor_simple_annotator",
            "predictor_simple"
        ]
    
    def predict(self) -> Tuple[Optional[str], float, int]:
        """
        Predict structured annotations based on the raw metadata.

        This method uses three predictors in sequence:
        1. PredictorSeperator to split the metadata.
        2. PredictorSimpleAnnotation to generate annotations.
        3. PredictorSimple to process the remaining metadata.

        Returns:
            Tuple[Optional[str], float, int]: 
                - The merged XML annotation (or None if prediction fails)
                - The total cost of the prediction
                - The total number of attempts made
        """
        print(f"Predicting for {self.name}, attempt: {self.attempts}")

        # Step 1: Separate the metadata
        response_sep, sep_cost, sep_attempts = PredictorSeperator(
            f"Here is the raw metadata \n{self.raw_metadata}").predict()
        
        if response_sep is None:
            print("Separation failed. Aborting prediction.")
            return None, sep_cost, sep_attempts
        
        response_annot, response_ome = response_sep

        # Step 2: Generate annotations
        self.pred_response_annot, annot_cost, annot_attempts = PredictorSimpleAnnotation(
            f"Here is the preselected raw metadata \n{response_annot}").predict()
        
        # Step 3: Process remaining metadata
        self.pred_response_ome, ome_cost, ome_attempts = PredictorSimple(
            f"Here is the preselected raw metadata \n{response_ome}").predict()
        
        total_attempts = sep_attempts + annot_attempts + ome_attempts
        self.add_attempts(total_attempts)

        # Merge the results
        response = utils.merge_xml_annotation(
            annot=self.pred_response_annot,
            ome=self.pred_response_ome)
        
        total_cost = sep_cost + annot_cost + ome_cost
        
        return response, total_cost, self.attempts