#!/bin/bash

# Define the directory containing the files
DIRECTORY="/home/aaron/mambaforge/envs/metagpt/lib/python3.12/site-packages/ome_types/_autogenerated/ome_2016_06"

# Process each file in the directory
for file in "$DIRECTORY"/*
do
  echo "Processing $file"
  # Use awk to comment out lines from 'metadata={' to the closing '}'
  awk '
  /metadata={/ {
    print "#" $0;  # Comment out the initial line containing metadata={
    in_comment_block=1;  # Start of comment block
    next;
  }
  in_comment_block {
    print "#" $0;  # Comment out all lines until the closing }
    if (/{/ && !/}/) {  # Check if there are nested opening brackets without a closing
      nested_brackets++;
    }
    if (/}/) {
      if (nested_brackets > 0) {  # Handle nested closing brackets
        nested_brackets--;
      } else {
        in_comment_block=0;  # End of comment block
      }
    }
    next;
  }
  { print }  # Print lines that do not fall into the above categories
  ' "$file" > temp && mv temp "$file"
done
